name: portraitsbyrach
favicon: null
layout_spectrum: 0.7528
typography_spectrum: 0.3853387380950153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#f8f8f8'
    - '#141414'
    - '#3e3e3e'
    - '#adadad'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.5550570103805512
purpose: []
